version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "Uploading JAR to deployment bucket from codebuild container"
      - |
        JAR_FILE=$(find target -name "*.jar" ! -name "*.original")
        echo "Found JAR: $JAR_FILE"
        aws s3 cp "$JAR_FILE" s3://"$BUCKET_NAME"/ems-app.jar
      
# This section is ONLY for CodePipeline bookkeeping coz we are using codepipeline so it will 
# push artifact in .zip format anyways...
# EC2 will NEVER use this
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
